
2023-10-22 21:52:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-22 21:54:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 21:56:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 21:58:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 22:00:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 22:02:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 22:04:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-22 22:06:02


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-22 22:08:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-22 22:10:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-22 22:12:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-22 22:14:02


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-22 22:16:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-22 22:18:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-22 22:20:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-22 22:22:02


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-22 22:24:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-22 22:26:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-22 22:28:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-22 22:30:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-22 22:32:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-22 22:34:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-22 22:36:20



2023-10-22 22:38:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 22:40:02


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process
NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 22:42:02


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 22:44:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 22:46:02


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 22:48:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 22:50:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 22:52:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 22:54:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 22:56:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 22:58:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:00:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:02:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:04:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:06:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:08:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:10:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:12:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:14:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:16:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:18:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:20:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:22:02


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:24:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:26:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:28:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:30:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:32:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:34:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:36:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:38:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:40:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:42:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:44:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:46:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:48:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:50:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:52:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:54:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:56:02


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-22 23:58:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 00:00:02


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 00:02:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 00:04:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 00:06:01

NO INTERNET
rmmod: ERROR: Module simcom_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:08:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:10:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:12:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:14:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:16:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:18:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:20:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:22:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:24:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:26:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:28:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:30:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:32:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:34:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:36:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:38:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:40:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:42:02


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:44:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:46:02


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:48:02

ping: connect: Network is unreachable
NO INTERNET
rmmod: ERROR: Module simcom_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

setup_target: failed to determine route to 172.21.70.0
setup_target: failed to determine route to 172.21.70.1
setup_target: failed to determine route to 172.21.70.2
setup_target: failed to determine route to 172.21.70.3
setup_target: failed to determine route to 172.21.70.4
setup_target: failed to determine route to 172.21.70.5
setup_target: failed to determine route to 172.21.70.6
setup_target: failed to determine route to 172.21.70.7
setup_target: failed to determine route to 172.21.70.8
setup_target: failed to determine route to 172.21.70.9
setup_target: failed to determine route to 172.21.70.10
setup_target: failed to determine route to 172.21.70.11
setup_target: failed to determine route to 172.21.70.12
setup_target: failed to determine route to 172.21.70.13
setup_target: failed to determine route to 172.21.70.14
setup_target: failed to determine route to 172.21.70.15
setup_target: failed to determine route to 172.21.70.16
setup_target: failed to determine route to 172.21.70.17
setup_target: failed to determine route to 172.21.70.18
setup_target: failed to determine route to 172.21.70.19
setup_target: failed to determine route to 172.21.70.20
setup_target: failed to determine route to 172.21.70.21
setup_target: failed to determine route to 172.21.70.22
setup_target: failed to determine route to 172.21.70.23
setup_target: failed to determine route to 172.21.70.24
setup_target: failed to determine route to 172.21.70.25
setup_target: failed to determine route to 172.21.70.26
setup_target: failed to determine route to 172.21.70.27
setup_target: failed to determine route to 172.21.70.28
setup_target: failed to determine route to 172.21.70.29
setup_target: failed to determine route to 172.21.70.30
setup_target: failed to determine route to 172.21.70.31
setup_target: failed to determine route to 172.21.70.32
setup_target: failed to determine route to 172.21.70.33
setup_target: failed to determine route to 172.21.70.34
setup_target: failed to determine route to 172.21.70.35
setup_target: failed to determine route to 172.21.70.36
setup_target: failed to determine route to 172.21.70.37
setup_target: failed to determine route to 172.21.70.38
setup_target: failed to determine route to 172.21.70.39
setup_target: failed to determine route to 172.21.70.40
setup_target: failed to determine route to 172.21.70.41
setup_target: failed to determine route to 172.21.70.42
setup_target: failed to determine route to 172.21.70.43
setup_target: failed to determine route to 172.21.70.44
setup_target: failed to determine route to 172.21.70.45
setup_target: failed to determine route to 172.21.70.46
setup_target: failed to determine route to 172.21.70.47
setup_target: failed to determine route to 172.21.70.48
setup_target: failed to determine route to 172.21.70.49
setup_target: failed to determine route to 172.21.70.50
setup_target: failed to determine route to 172.21.70.51
setup_target: failed to determine route to 172.21.70.52
setup_target: failed to determine route to 172.21.70.53
setup_target: failed to determine route to 172.21.70.54
setup_target: failed to determine route to 172.21.70.55
setup_target: failed to determine route to 172.21.70.56
setup_target: failed to determine route to 172.21.70.57
setup_target: failed to determine route to 172.21.70.58
setup_target: failed to determine route to 172.21.70.59
setup_target: failed to determine route to 172.21.70.60
setup_target: failed to determine route to 172.21.70.61
setup_target: failed to determine route to 172.21.70.62
setup_target: failed to determine route to 172.21.70.63
setup_target: failed to determine route to 172.21.70.64
setup_target: failed to determine route to 172.21.70.65
setup_target: failed to determine route to 172.21.70.66
setup_target: failed to determine route to 172.21.70.67
setup_target: failed to determine route to 172.21.70.68
setup_target: failed to determine route to 172.21.70.69
setup_target: failed to determine route to 172.21.70.70
setup_target: failed to determine route to 172.21.70.71
setup_target: failed to determine route to 172.21.70.72
setup_target: failed to determine route to 172.21.70.73
setup_target: failed to determine route to 172.21.70.74
setup_target: failed to determine route to 172.21.70.75
setup_target: failed to determine route to 172.21.70.76
setup_target: failed to determine route to 172.21.70.77
setup_target: failed to determine route to 172.21.70.78
setup_target: failed to determine route to 172.21.70.79
setup_target: failed to determine route to 172.21.70.80
setup_target: failed to determine route to 172.21.70.81
setup_target: failed to determine route to 172.21.70.82
setup_target: failed to determine route to 172.21.70.83
setup_target: failed to determine route to 172.21.70.84
setup_target: failed to determine route to 172.21.70.85
setup_target: failed to determine route to 172.21.70.86
setup_target: failed to determine route to 172.21.70.87
setup_target: failed to determine route to 172.21.70.88
setup_target: failed to determine route to 172.21.70.89
setup_target: failed to determine route to 172.21.70.90
setup_target: failed to determine route to 172.21.70.91
setup_target: failed to determine route to 172.21.70.92
setup_target: failed to determine route to 172.21.70.93
setup_target: failed to determine route to 172.21.70.94
setup_target: failed to determine route to 172.21.70.95
setup_target: failed to determine route to 172.21.70.96
setup_target: failed to determine route to 172.21.70.97
setup_target: failed to determine route to 172.21.70.98
setup_target: failed to determine route to 172.21.70.99
setup_target: failed to determine route to 172.21.70.100
setup_target: failed to determine route to 172.21.70.101
setup_target: failed to determine route to 172.21.70.102
setup_target: failed to determine route to 172.21.70.103
setup_target: failed to determine route to 172.21.70.104
setup_target: failed to determine route to 172.21.70.105
setup_target: failed to determine route to 172.21.70.106
setup_target: failed to determine route to 172.21.70.107
setup_target: failed to determine route to 172.21.70.108
setup_target: failed to determine route to 172.21.70.109
setup_target: failed to determine route to 172.21.70.110
setup_target: failed to determine route to 172.21.70.111
setup_target: failed to determine route to 172.21.70.112
setup_target: failed to determine route to 172.21.70.113
setup_target: failed to determine route to 172.21.70.114
setup_target: failed to determine route to 172.21.70.115
setup_target: failed to determine route to 172.21.70.116
setup_target: failed to determine route to 172.21.70.117
setup_target: failed to determine route to 172.21.70.118
setup_target: failed to determine route to 172.21.70.119
setup_target: failed to determine route to 172.21.70.120
setup_target: failed to determine route to 172.21.70.121
setup_target: failed to determine route to 172.21.70.122
setup_target: failed to determine route to 172.21.70.123
setup_target: failed to determine route to 172.21.70.124
setup_target: failed to determine route to 172.21.70.125
setup_target: failed to determine route to 172.21.70.126
setup_target: failed to determine route to 172.21.70.127
setup_target: failed to determine route to 172.21.70.128
setup_target: failed to determine route to 172.21.70.129
setup_target: failed to determine route to 172.21.70.130
setup_target: failed to determine route to 172.21.70.131
setup_target: failed to determine route to 172.21.70.132
setup_target: failed to determine route to 172.21.70.133
setup_target: failed to determine route to 172.21.70.134
setup_target: failed to determine route to 172.21.70.135
setup_target: failed to determine route to 172.21.70.136
setup_target: failed to determine route to 172.21.70.137
setup_target: failed to determine route to 172.21.70.138
setup_target: failed to determine route to 172.21.70.139
setup_target: failed to determine route to 172.21.70.140
setup_target: failed to determine route to 172.21.70.141
setup_target: failed to determine route to 172.21.70.142
setup_target: failed to determine route to 172.21.70.143
setup_target: failed to determine route to 172.21.70.144
setup_target: failed to determine route to 172.21.70.145
setup_target: failed to determine route to 172.21.70.146
setup_target: failed to determine route to 172.21.70.147
setup_target: failed to determine route to 172.21.70.148
setup_target: failed to determine route to 172.21.70.149
setup_target: failed to determine route to 172.21.70.150
setup_target: failed to determine route to 172.21.70.151
setup_target: failed to determine route to 172.21.70.152
setup_target: failed to determine route to 172.21.70.153
setup_target: failed to determine route to 172.21.70.154
setup_target: failed to determine route to 172.21.70.155
setup_target: failed to determine route to 172.21.70.156
setup_target: failed to determine route to 172.21.70.157
setup_target: failed to determine route to 172.21.70.158
setup_target: failed to determine route to 172.21.70.159
setup_target: failed to determine route to 172.21.70.160
setup_target: failed to determine route to 172.21.70.161
setup_target: failed to determine route to 172.21.70.162
setup_target: failed to determine route to 172.21.70.163
setup_target: failed to determine route to 172.21.70.164
setup_target: failed to determine route to 172.21.70.165
setup_target: failed to determine route to 172.21.70.166
setup_target: failed to determine route to 172.21.70.167
setup_target: failed to determine route to 172.21.70.168
setup_target: failed to determine route to 172.21.70.169
setup_target: failed to determine route to 172.21.70.170
setup_target: failed to determine route to 172.21.70.171
setup_target: failed to determine route to 172.21.70.172
setup_target: failed to determine route to 172.21.70.173
setup_target: failed to determine route to 172.21.70.174
setup_target: failed to determine route to 172.21.70.175
setup_target: failed to determine route to 172.21.70.176
setup_target: failed to determine route to 172.21.70.177
setup_target: failed to determine route to 172.21.70.178
setup_target: failed to determine route to 172.21.70.179
setup_target: failed to determine route to 172.21.70.180
setup_target: failed to determine route to 172.21.70.181
setup_target: failed to determine route to 172.21.70.182
setup_target: failed to determine route to 172.21.70.183
setup_target: failed to determine route to 172.21.70.184
setup_target: failed to determine route to 172.21.70.185
setup_target: failed to determine route to 172.21.70.186
setup_target: failed to determine route to 172.21.70.187
setup_target: failed to determine route to 172.21.70.188
setup_target: failed to determine route to 172.21.70.189
setup_target: failed to determine route to 172.21.70.190
setup_target: failed to determine route to 172.21.70.191
setup_target: failed to determine route to 172.21.70.192
setup_target: failed to determine route to 172.21.70.193
setup_target: failed to determine route to 172.21.70.194
setup_target: failed to determine route to 172.21.70.195
setup_target: failed to determine route to 172.21.70.196
setup_target: failed to determine route to 172.21.70.197
setup_target: failed to determine route to 172.21.70.198
setup_target: failed to determine route to 172.21.70.199
setup_target: failed to determine route to 172.21.70.200
setup_target: failed to determine route to 172.21.70.201
setup_target: failed to determine route to 172.21.70.202
setup_target: failed to determine route to 172.21.70.203
setup_target: failed to determine route to 172.21.70.204
setup_target: failed to determine route to 172.21.70.205
setup_target: failed to determine route to 172.21.70.206
setup_target: failed to determine route to 172.21.70.207
setup_target: failed to determine route to 172.21.70.208
setup_target: failed to determine route to 172.21.70.209
setup_target: failed to determine route to 172.21.70.210
setup_target: failed to determine route to 172.21.70.211
setup_target: failed to determine route to 172.21.70.212
setup_target: failed to determine route to 172.21.70.213
setup_target: failed to determine route to 172.21.70.214
setup_target: failed to determine route to 172.21.70.215
setup_target: failed to determine route to 172.21.70.216
setup_target: failed to determine route to 172.21.70.217
setup_target: failed to determine route to 172.21.70.218
setup_target: failed to determine route to 172.21.70.219
setup_target: failed to determine route to 172.21.70.220
setup_target: failed to determine route to 172.21.70.221
setup_target: failed to determine route to 172.21.70.222
setup_target: failed to determine route to 172.21.70.223
setup_target: failed to determine route to 172.21.70.224
setup_target: failed to determine route to 172.21.70.225
setup_target: failed to determine route to 172.21.70.226
setup_target: failed to determine route to 172.21.70.227
setup_target: failed to determine route to 172.21.70.228
setup_target: failed to determine route to 172.21.70.229
setup_target: failed to determine route to 172.21.70.230
setup_target: failed to determine route to 172.21.70.231
setup_target: failed to determine route to 172.21.70.232
setup_target: failed to determine route to 172.21.70.233
setup_target: failed to determine route to 172.21.70.234
setup_target: failed to determine route to 172.21.70.235
setup_target: failed to determine route to 172.21.70.236
setup_target: failed to determine route to 172.21.70.237
setup_target: failed to determine route to 172.21.70.238
setup_target: failed to determine route to 172.21.70.239
setup_target: failed to determine route to 172.21.70.240
setup_target: failed to determine route to 172.21.70.241
setup_target: failed to determine route to 172.21.70.242
setup_target: failed to determine route to 172.21.70.243
setup_target: failed to determine route to 172.21.70.244
setup_target: failed to determine route to 172.21.70.245
setup_target: failed to determine route to 172.21.70.246
setup_target: failed to determine route to 172.21.70.247
setup_target: failed to determine route to 172.21.70.248
setup_target: failed to determine route to 172.21.70.249
setup_target: failed to determine route to 172.21.70.250
setup_target: failed to determine route to 172.21.70.251
setup_target: failed to determine route to 172.21.70.252
setup_target: failed to determine route to 172.21.70.253
setup_target: failed to determine route to 172.21.70.254
setup_target: failed to determine route to 172.21.70.255
WARNING: No targets were specified, so 0 hosts scanned.
NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:50:01

ping: connect: Network is unreachable
NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

mass_dns: warning: Unable to determine any DNS servers. Reverse DNS is disabled. Try using --system-dns or specify valid servers with --dns-servers
NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:52:02

ping: connect: Network is unreachable
NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

mass_dns: warning: Unable to determine any DNS servers. Reverse DNS is disabled. Try using --system-dns or specify valid servers with --dns-servers
NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:54:01

ping: connect: Network is unreachable
NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

mass_dns: warning: Unable to determine any DNS servers. Reverse DNS is disabled. Try using --system-dns or specify valid servers with --dns-servers
NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:56:01

ping: connect: Network is unreachable
NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

mass_dns: warning: Unable to determine any DNS servers. Reverse DNS is disabled. Try using --system-dns or specify valid servers with --dns-servers
NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 00:58:01

ping: connect: Network is unreachable
NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

mass_dns: warning: Unable to determine any DNS servers. Reverse DNS is disabled. Try using --system-dns or specify valid servers with --dns-servers
NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 01:00:02

ping: connect: Network is unreachable
NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

mass_dns: warning: Unable to determine any DNS servers. Reverse DNS is disabled. Try using --system-dns or specify valid servers with --dns-servers
NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 01:02:01

ping: connect: Network is unreachable
NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

mass_dns: warning: Unable to determine any DNS servers. Reverse DNS is disabled. Try using --system-dns or specify valid servers with --dns-servers
NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 01:04:01

ping: connect: Network is unreachable
NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

mass_dns: warning: Unable to determine any DNS servers. Reverse DNS is disabled. Try using --system-dns or specify valid servers with --dns-servers
NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 01:06:01

ping: connect: Network is unreachable
NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

mass_dns: warning: Unable to determine any DNS servers. Reverse DNS is disabled. Try using --system-dns or specify valid servers with --dns-servers
NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 01:08:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 09:50:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 09:52:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 09:54:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 09:56:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 09:58:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:00:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:02:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:04:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:06:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:08:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:10:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:12:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:14:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:16:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:18:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:20:02

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device

2023-10-23 10:22:02


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:24:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:26:02


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:28:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:30:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:32:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:34:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:36:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:38:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:40:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:42:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:44:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:46:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:48:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:50:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:52:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:54:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:56:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 10:58:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:00:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:02:02


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:04:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:06:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:08:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:10:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:12:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:14:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:16:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:18:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:20:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:22:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:24:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:26:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:28:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:30:02


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:32:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:34:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:36:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:38:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:40:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:42:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:44:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:46:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:48:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:50:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:52:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:54:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:56:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 11:58:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:00:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:02:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:04:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:06:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:08:02


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:10:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:12:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:14:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:16:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:18:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:20:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:22:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:24:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:26:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:28:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:30:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:32:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:34:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:36:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:38:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:40:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:42:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:44:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:46:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:48:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:50:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:52:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:54:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:56:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 12:58:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 13:00:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 13:02:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 13:04:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 13:06:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 13:08:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 13:10:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 13:12:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 13:14:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 13:16:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 13:18:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 13:20:01

ping: connect: ネットワークに届きません
NO INTERNET
rmmod: ERROR: Module simcom_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: インタフェースフラグの取得中にエラーが発生しました:そのようなデバイスはありません
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 72, in <module>
    send_at('AT$QCRMCALL=1,1','OK',2)
  File "/home/niw/NIW/simhat_code/dial.py", line 32, in send_at
    if sim.inWaiting():
       ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 594, in inWaiting
    return self.in_waiting
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 549, in in_waiting
    s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 5] Input/output error

setup_target: failed to determine route to 172.21.70.0
setup_target: failed to determine route to 172.21.70.1
setup_target: failed to determine route to 172.21.70.2
setup_target: failed to determine route to 172.21.70.3
setup_target: failed to determine route to 172.21.70.4
setup_target: failed to determine route to 172.21.70.5
setup_target: failed to determine route to 172.21.70.6
setup_target: failed to determine route to 172.21.70.7
setup_target: failed to determine route to 172.21.70.8
setup_target: failed to determine route to 172.21.70.9
setup_target: failed to determine route to 172.21.70.10
setup_target: failed to determine route to 172.21.70.11
setup_target: failed to determine route to 172.21.70.12
setup_target: failed to determine route to 172.21.70.13
setup_target: failed to determine route to 172.21.70.14
setup_target: failed to determine route to 172.21.70.15
setup_target: failed to determine route to 172.21.70.16
setup_target: failed to determine route to 172.21.70.17
setup_target: failed to determine route to 172.21.70.18
setup_target: failed to determine route to 172.21.70.19
setup_target: failed to determine route to 172.21.70.20
setup_target: failed to determine route to 172.21.70.21
setup_target: failed to determine route to 172.21.70.22
setup_target: failed to determine route to 172.21.70.23
setup_target: failed to determine route to 172.21.70.24
setup_target: failed to determine route to 172.21.70.25
setup_target: failed to determine route to 172.21.70.26
setup_target: failed to determine route to 172.21.70.27
setup_target: failed to determine route to 172.21.70.28
setup_target: failed to determine route to 172.21.70.29
setup_target: failed to determine route to 172.21.70.30
setup_target: failed to determine route to 172.21.70.31
setup_target: failed to determine route to 172.21.70.32
setup_target: failed to determine route to 172.21.70.33
setup_target: failed to determine route to 172.21.70.34
setup_target: failed to determine route to 172.21.70.35
setup_target: failed to determine route to 172.21.70.36
setup_target: failed to determine route to 172.21.70.37
setup_target: failed to determine route to 172.21.70.38
setup_target: failed to determine route to 172.21.70.39
setup_target: failed to determine route to 172.21.70.40
setup_target: failed to determine route to 172.21.70.41
setup_target: failed to determine route to 172.21.70.42
setup_target: failed to determine route to 172.21.70.43
setup_target: failed to determine route to 172.21.70.44
setup_target: failed to determine route to 172.21.70.45
setup_target: failed to determine route to 172.21.70.46
setup_target: failed to determine route to 172.21.70.47
setup_target: failed to determine route to 172.21.70.48
setup_target: failed to determine route to 172.21.70.49
setup_target: failed to determine route to 172.21.70.50
setup_target: failed to determine route to 172.21.70.51
setup_target: failed to determine route to 172.21.70.52
setup_target: failed to determine route to 172.21.70.53
setup_target: failed to determine route to 172.21.70.54
setup_target: failed to determine route to 172.21.70.55
setup_target: failed to determine route to 172.21.70.56
setup_target: failed to determine route to 172.21.70.57
setup_target: failed to determine route to 172.21.70.58
setup_target: failed to determine route to 172.21.70.59
setup_target: failed to determine route to 172.21.70.60
setup_target: failed to determine route to 172.21.70.61
setup_target: failed to determine route to 172.21.70.62
setup_target: failed to determine route to 172.21.70.63
setup_target: failed to determine route to 172.21.70.64
setup_target: failed to determine route to 172.21.70.65
setup_target: failed to determine route to 172.21.70.66
setup_target: failed to determine route to 172.21.70.67
setup_target: failed to determine route to 172.21.70.68
setup_target: failed to determine route to 172.21.70.69
setup_target: failed to determine route to 172.21.70.70
setup_target: failed to determine route to 172.21.70.71
setup_target: failed to determine route to 172.21.70.72
setup_target: failed to determine route to 172.21.70.73
setup_target: failed to determine route to 172.21.70.74
setup_target: failed to determine route to 172.21.70.75
setup_target: failed to determine route to 172.21.70.76
setup_target: failed to determine route to 172.21.70.77
setup_target: failed to determine route to 172.21.70.78
setup_target: failed to determine route to 172.21.70.79
setup_target: failed to determine route to 172.21.70.80
setup_target: failed to determine route to 172.21.70.81
setup_target: failed to determine route to 172.21.70.82
setup_target: failed to determine route to 172.21.70.83
setup_target: failed to determine route to 172.21.70.84
setup_target: failed to determine route to 172.21.70.85
setup_target: failed to determine route to 172.21.70.86
setup_target: failed to determine route to 172.21.70.87
setup_target: failed to determine route to 172.21.70.88
setup_target: failed to determine route to 172.21.70.89
setup_target: failed to determine route to 172.21.70.90
setup_target: failed to determine route to 172.21.70.91
setup_target: failed to determine route to 172.21.70.92
setup_target: failed to determine route to 172.21.70.93
setup_target: failed to determine route to 172.21.70.94
setup_target: failed to determine route to 172.21.70.95
setup_target: failed to determine route to 172.21.70.96
setup_target: failed to determine route to 172.21.70.97
setup_target: failed to determine route to 172.21.70.98
setup_target: failed to determine route to 172.21.70.99
setup_target: failed to determine route to 172.21.70.100
setup_target: failed to determine route to 172.21.70.101
setup_target: failed to determine route to 172.21.70.102
setup_target: failed to determine route to 172.21.70.103
setup_target: failed to determine route to 172.21.70.104
setup_target: failed to determine route to 172.21.70.105
setup_target: failed to determine route to 172.21.70.106
setup_target: failed to determine route to 172.21.70.107
setup_target: failed to determine route to 172.21.70.108
setup_target: failed to determine route to 172.21.70.109
setup_target: failed to determine route to 172.21.70.110
setup_target: failed to determine route to 172.21.70.111
setup_target: failed to determine route to 172.21.70.112
setup_target: failed to determine route to 172.21.70.113
setup_target: failed to determine route to 172.21.70.114
setup_target: failed to determine route to 172.21.70.115
setup_target: failed to determine route to 172.21.70.116
setup_target: failed to determine route to 172.21.70.117
setup_target: failed to determine route to 172.21.70.118
setup_target: failed to determine route to 172.21.70.119
setup_target: failed to determine route to 172.21.70.120
setup_target: failed to determine route to 172.21.70.121
setup_target: failed to determine route to 172.21.70.122
setup_target: failed to determine route to 172.21.70.123
setup_target: failed to determine route to 172.21.70.124
setup_target: failed to determine route to 172.21.70.125
setup_target: failed to determine route to 172.21.70.126
setup_target: failed to determine route to 172.21.70.127
setup_target: failed to determine route to 172.21.70.128
setup_target: failed to determine route to 172.21.70.129
setup_target: failed to determine route to 172.21.70.130
setup_target: failed to determine route to 172.21.70.131
setup_target: failed to determine route to 172.21.70.132
setup_target: failed to determine route to 172.21.70.133
setup_target: failed to determine route to 172.21.70.134
setup_target: failed to determine route to 172.21.70.135
setup_target: failed to determine route to 172.21.70.136
setup_target: failed to determine route to 172.21.70.137
setup_target: failed to determine route to 172.21.70.138
setup_target: failed to determine route to 172.21.70.139
setup_target: failed to determine route to 172.21.70.140
setup_target: failed to determine route to 172.21.70.141
setup_target: failed to determine route to 172.21.70.142
setup_target: failed to determine route to 172.21.70.143
setup_target: failed to determine route to 172.21.70.144
setup_target: failed to determine route to 172.21.70.145
setup_target: failed to determine route to 172.21.70.146
setup_target: failed to determine route to 172.21.70.147
setup_target: failed to determine route to 172.21.70.148
setup_target: failed to determine route to 172.21.70.149
setup_target: failed to determine route to 172.21.70.150
setup_target: failed to determine route to 172.21.70.151
setup_target: failed to determine route to 172.21.70.152
setup_target: failed to determine route to 172.21.70.153
setup_target: failed to determine route to 172.21.70.154
setup_target: failed to determine route to 172.21.70.155
setup_target: failed to determine route to 172.21.70.156
setup_target: failed to determine route to 172.21.70.157
setup_target: failed to determine route to 172.21.70.158
setup_target: failed to determine route to 172.21.70.159
setup_target: failed to determine route to 172.21.70.160
setup_target: failed to determine route to 172.21.70.161
setup_target: failed to determine route to 172.21.70.162
setup_target: failed to determine route to 172.21.70.163
setup_target: failed to determine route to 172.21.70.164
setup_target: failed to determine route to 172.21.70.165
setup_target: failed to determine route to 172.21.70.166
setup_target: failed to determine route to 172.21.70.167
setup_target: failed to determine route to 172.21.70.168
setup_target: failed to determine route to 172.21.70.169
setup_target: failed to determine route to 172.21.70.170
setup_target: failed to determine route to 172.21.70.171
setup_target: failed to determine route to 172.21.70.172
setup_target: failed to determine route to 172.21.70.173
setup_target: failed to determine route to 172.21.70.174
setup_target: failed to determine route to 172.21.70.175
setup_target: failed to determine route to 172.21.70.176
setup_target: failed to determine route to 172.21.70.177
setup_target: failed to determine route to 172.21.70.178
setup_target: failed to determine route to 172.21.70.179
setup_target: failed to determine route to 172.21.70.180
setup_target: failed to determine route to 172.21.70.181
setup_target: failed to determine route to 172.21.70.182
setup_target: failed to determine route to 172.21.70.183
setup_target: failed to determine route to 172.21.70.184
setup_target: failed to determine route to 172.21.70.185
setup_target: failed to determine route to 172.21.70.186
setup_target: failed to determine route to 172.21.70.187
setup_target: failed to determine route to 172.21.70.188
setup_target: failed to determine route to 172.21.70.189
setup_target: failed to determine route to 172.21.70.190
setup_target: failed to determine route to 172.21.70.191
setup_target: failed to determine route to 172.21.70.192
setup_target: failed to determine route to 172.21.70.193
setup_target: failed to determine route to 172.21.70.194
setup_target: failed to determine route to 172.21.70.195
setup_target: failed to determine route to 172.21.70.196
setup_target: failed to determine route to 172.21.70.197
setup_target: failed to determine route to 172.21.70.198
setup_target: failed to determine route to 172.21.70.199
setup_target: failed to determine route to 172.21.70.200
setup_target: failed to determine route to 172.21.70.201
setup_target: failed to determine route to 172.21.70.202
setup_target: failed to determine route to 172.21.70.203
setup_target: failed to determine route to 172.21.70.204
setup_target: failed to determine route to 172.21.70.205
setup_target: failed to determine route to 172.21.70.206
setup_target: failed to determine route to 172.21.70.207
setup_target: failed to determine route to 172.21.70.208
setup_target: failed to determine route to 172.21.70.209
setup_target: failed to determine route to 172.21.70.210
setup_target: failed to determine route to 172.21.70.211
setup_target: failed to determine route to 172.21.70.212
setup_target: failed to determine route to 172.21.70.213
setup_target: failed to determine route to 172.21.70.214
setup_target: failed to determine route to 172.21.70.215
setup_target: failed to determine route to 172.21.70.216
setup_target: failed to determine route to 172.21.70.217
setup_target: failed to determine route to 172.21.70.218
setup_target: failed to determine route to 172.21.70.219
setup_target: failed to determine route to 172.21.70.220
setup_target: failed to determine route to 172.21.70.221
setup_target: failed to determine route to 172.21.70.222
setup_target: failed to determine route to 172.21.70.223
setup_target: failed to determine route to 172.21.70.224
setup_target: failed to determine route to 172.21.70.225
setup_target: failed to determine route to 172.21.70.226
setup_target: failed to determine route to 172.21.70.227
setup_target: failed to determine route to 172.21.70.228
setup_target: failed to determine route to 172.21.70.229
setup_target: failed to determine route to 172.21.70.230
setup_target: failed to determine route to 172.21.70.231
setup_target: failed to determine route to 172.21.70.232
setup_target: failed to determine route to 172.21.70.233
setup_target: failed to determine route to 172.21.70.234
setup_target: failed to determine route to 172.21.70.235
setup_target: failed to determine route to 172.21.70.236
setup_target: failed to determine route to 172.21.70.237
setup_target: failed to determine route to 172.21.70.238
setup_target: failed to determine route to 172.21.70.239
setup_target: failed to determine route to 172.21.70.240
setup_target: failed to determine route to 172.21.70.241
setup_target: failed to determine route to 172.21.70.242
setup_target: failed to determine route to 172.21.70.243
setup_target: failed to determine route to 172.21.70.244
setup_target: failed to determine route to 172.21.70.245
setup_target: failed to determine route to 172.21.70.246
setup_target: failed to determine route to 172.21.70.247
setup_target: failed to determine route to 172.21.70.248
setup_target: failed to determine route to 172.21.70.249
setup_target: failed to determine route to 172.21.70.250
setup_target: failed to determine route to 172.21.70.251
setup_target: failed to determine route to 172.21.70.252
setup_target: failed to determine route to 172.21.70.253
setup_target: failed to determine route to 172.21.70.254
setup_target: failed to determine route to 172.21.70.255
WARNING: No targets were specified, so 0 hosts scanned.
NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 13:22:01

ping: connect: ネットワークに届きません
NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: インタフェースフラグの取得中にエラーが発生しました:そのようなデバイスはありません
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

mass_dns: warning: Unable to determine any DNS servers. Reverse DNS is disabled. Try using --system-dns or specify valid servers with --dns-servers
NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process
bash: warning: setlocale: LC_ALL: cannot change locale (ja_JP.UTF-8)

2023-10-23 13:24:01

ping: connect: Network is unreachable
NO INTERNET
bash: warning: setlocale: LC_ALL: cannot change locale (ja_JP.UTF-8)
bash: warning: setlocale: LC_ALL: cannot change locale (ja_JP.UTF-8)
rmmod: ERROR: Module qmi_wwan is not currently loaded
bash: warning: setlocale: LC_ALL: cannot change locale (ja_JP.UTF-8)
rm -rf *~ core .depend .*.cmd .tmp_versions
bash: warning: setlocale: LC_ALL: cannot change locale (ja_JP.UTF-8)
wwan0: ERROR while getting interface flags: No such device

2023-10-23 13:26:01



2023-10-23 13:28:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 13:30:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process
NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 13:32:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 13:34:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 13:36:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 13:38:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 13:40:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 13:42:02


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 13:44:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 13:46:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 13:48:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 13:50:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 13:52:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 13:54:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 13:56:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 13:58:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 14:00:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 14:02:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 14:04:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 14:06:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 14:08:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 14:10:02


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 14:12:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 14:14:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 14:16:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 14:18:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 14:20:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-23 14:22:01

NO INTERNET
rmmod: ERROR: Module simcom_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 14:24:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 14:26:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 14:28:20

NO INTERNET
rmmod: ERROR: Module simcom_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 72, in <module>
    send_at('AT$QCRMCALL=1,1','OK',2)
  File "/home/niw/NIW/simhat_code/dial.py", line 32, in send_at
    if sim.inWaiting():
       ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 594, in inWaiting
    return self.in_waiting
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 549, in in_waiting
    s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 5] Input/output error


2023-10-23 14:30:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.


2023-10-23 14:32:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 72, in <module>
    send_at('AT$QCRMCALL=1,1','OK',2)
  File "/home/niw/NIW/simhat_code/dial.py", line 32, in send_at
    if sim.inWaiting():
       ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 594, in inWaiting
    return self.in_waiting
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 549, in in_waiting
    s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 5] Input/output error

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process
NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 14:34:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 14:36:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 14:38:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 14:40:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 14:42:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 14:44:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 14:46:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 14:48:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 72, in <module>
    send_at('AT$QCRMCALL=1,1','OK',2)
  File "/home/niw/NIW/simhat_code/dial.py", line 32, in send_at
    if sim.inWaiting():
       ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 594, in inWaiting
    return self.in_waiting
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 549, in in_waiting
    s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 5] Input/output error

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 14:50:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 14:52:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 14:54:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 14:56:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 14:58:02

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 15:00:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 15:02:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 15:04:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 15:06:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 15:08:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device
udhcpc: SIOCGIFINDEX: No such device
command AT$QCRMCALL=1,1 failed
unexpected response:	
Traceback (most recent call last):
  File "/home/niw/NIW/simhat_code/dial.py", line 78, in <module>
    subprocess.run('sudo udhcpc -i wwan0', shell=True, timeout=6, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo udhcpc -i wwan0' returned non-zero exit status 1.

NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: No such process

2023-10-23 15:10:01

NO INTERNET
rmmod: ERROR: Module qmi_wwan is not currently loaded
rm -rf *~ core .depend .*.cmd .tmp_versions
wwan0: ERROR while getting interface flags: No such device

2023-10-24 09:28:01



2023-10-24 09:30:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process
NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-25 10:16:01


NO ROUTING FUNCTION

net.ipv4.ip_forward = 1
RTNETLINK answers: No such process

2023-10-25 10:18:01


2023-10-25 10:20:01



2023-10-25 10:22:01
2023-10-25 10:22:01




2023-10-25 10:24:01
2023-10-25 10:24:01




2023-10-25 10:26:01

2023-10-25 10:26:01



2023-10-25 10:28:01
2023-10-25 10:28:01




2023-10-25 10:30:01

2023-10-25 10:30:01



2023-10-25 10:32:01

2023-10-25 10:32:01



2023-10-25 10:34:01
2023-10-25 10:34:01




2023-10-25 10:36:01
2023-10-25 10:36:01




2023-10-25 10:38:01

2023-10-25 10:38:01



2023-10-25 10:40:01
2023-10-25 10:40:01



2023-10-25 10:42:02


2023-10-25 10:42:02



2023-10-25 10:44:01

2023-10-25 10:44:01



2023-10-25 10:46:01
2023-10-25 10:46:01



2023-10-25 10:48:01


2023-10-25 10:48:01



2023-10-25 10:50:01
2023-10-25 10:50:01




2023-10-25 10:52:01

2023-10-25 10:52:01


2023-10-25 10:54:01


2023-10-25 10:54:01


2023-10-25 10:56:01


2023-10-25 10:56:01



2023-10-25 10:58:01
2023-10-25 10:58:01




2023-10-25 11:00:01

2023-10-25 11:00:01



2023-10-25 11:02:01

2023-10-25 11:02:01


2023-10-25 11:04:01


2023-10-25 11:04:01



2023-10-25 11:06:01

2023-10-25 11:06:01



2023-10-25 11:08:01
2023-10-25 11:08:01




2023-10-25 11:10:01
2023-10-25 11:10:01




2023-10-25 11:12:01
2023-10-25 11:12:01




2023-10-25 11:14:01

2023-10-25 11:14:01



2023-10-25 11:16:01
2023-10-25 11:16:01




2023-10-25 11:18:01

2023-10-25 11:18:01



2023-10-25 11:20:01
2023-10-25 11:20:01




2023-10-25 11:22:01
2023-10-25 11:22:01



2023-10-25 11:24:01


2023-10-25 11:24:01


2023-10-25 11:26:01


2023-10-25 11:26:01



2023-10-25 11:28:01

2023-10-25 11:28:01



2023-10-25 11:30:01

2023-10-25 11:30:01



2023-10-25 11:32:01
2023-10-25 11:32:01



2023-10-25 11:34:01


2023-10-25 11:34:01


2023-10-25 11:36:01


2023-10-25 11:36:01



2023-10-25 11:38:01

2023-10-25 11:38:01



2023-10-25 11:40:02
2023-10-25 11:40:02




2023-10-25 11:42:01
2023-10-25 11:42:01




2023-10-25 11:44:01
2023-10-25 11:44:01




2023-10-25 11:46:01

2023-10-25 11:46:01



2023-10-25 11:48:01
2023-10-25 11:48:01




2023-10-25 11:50:01

2023-10-25 11:50:01



2023-10-25 11:52:01

2023-10-25 11:52:01



2023-10-25 11:54:01
2023-10-25 11:54:01




2023-10-25 11:56:01
2023-10-25 11:56:01



2023-10-25 11:58:01


2023-10-25 11:58:01



2023-10-25 12:00:01
2023-10-25 12:00:01




2023-10-25 12:02:01

2023-10-25 12:02:01



2023-10-25 12:04:01

2023-10-25 12:04:01



2023-10-25 12:06:01
2023-10-25 12:06:01




2023-10-25 12:08:02
2023-10-25 12:08:02




2023-10-25 12:10:01

2023-10-25 12:10:01



2023-10-25 12:12:01

2023-10-25 12:12:01



2023-10-25 12:14:01

2023-10-25 12:14:01



2023-10-25 12:16:01

2023-10-25 12:16:01



2023-10-25 12:18:01

2023-10-25 12:18:01



2023-10-25 12:20:01

2023-10-25 12:20:01



2023-10-25 12:22:01
2023-10-25 12:22:01




2023-10-25 12:24:01

2023-10-25 12:24:01



2023-10-25 12:26:01
2023-10-25 12:26:01




2023-10-25 12:28:01

2023-10-25 12:28:01



2023-10-25 12:30:01

2023-10-25 12:30:01



2023-10-25 12:32:02

2023-10-25 12:32:02



2023-10-25 12:34:01

2023-10-25 12:34:01



2023-10-25 12:36:01
2023-10-25 12:36:01




2023-10-25 12:38:01

2023-10-25 12:38:01



2023-10-25 12:40:01
2023-10-25 12:40:01




2023-10-25 12:42:01

2023-10-25 12:42:01



2023-10-25 12:44:01
2023-10-25 12:44:01



2023-10-25 12:46:01


2023-10-25 12:46:01


2023-10-25 12:48:01


2023-10-25 12:48:01



2023-10-25 12:50:01

2023-10-25 12:50:01


2023-10-25 12:52:01


2023-10-25 12:52:01


2023-10-25 12:54:01


2023-10-25 12:54:01



2023-10-25 12:56:01

2023-10-25 12:56:01



2023-10-25 12:58:01

2023-10-25 12:58:01



2023-10-25 13:00:01
2023-10-25 13:00:01




2023-10-25 13:02:02

2023-10-25 13:02:02



2023-10-25 13:04:01
2023-10-25 13:04:01




2023-10-25 13:06:01

2023-10-25 13:06:01



2023-10-25 13:08:01
2023-10-25 13:08:01




2023-10-25 13:10:01
2023-10-25 13:10:01



2023-10-25 13:12:01


2023-10-25 13:12:01



2023-10-25 13:14:01

2023-10-25 13:14:01



2023-10-25 13:16:01
2023-10-25 13:16:01




2023-10-25 13:18:01

2023-10-25 13:18:01


2023-10-25 13:20:01


2023-10-25 13:20:01


2023-10-25 13:22:01


2023-10-25 13:22:01



2023-10-25 13:24:01

2023-10-25 13:24:01



2023-10-25 13:26:02
2023-10-25 13:26:02




2023-10-25 13:28:01

2023-10-25 13:28:01



2023-10-25 13:30:01
2023-10-25 13:30:01




2023-10-25 13:32:01

2023-10-25 13:32:01



2023-10-25 13:34:01
2023-10-25 13:34:01




2023-10-25 13:36:01

2023-10-25 13:36:01



2023-10-25 13:38:01
2023-10-25 13:38:01




2023-10-25 13:40:01
2023-10-25 13:40:01




2023-10-25 13:42:01
2023-10-25 13:42:01




2023-10-25 13:44:01
2023-10-25 13:44:01



2023-10-25 13:46:01


2023-10-25 13:46:01



2023-10-25 13:48:01
2023-10-25 13:48:01




2023-10-25 13:50:01
2023-10-25 13:50:01




2023-10-25 13:52:01
2023-10-25 13:52:01



2023-10-25 13:54:01


2023-10-25 13:54:01



2023-10-25 13:56:01

2023-10-25 13:56:01



2023-10-25 13:58:02
2023-10-25 13:58:02




2023-10-25 14:00:01

2023-10-25 14:00:01



2023-10-25 14:02:01

2023-10-25 14:02:01



2023-10-25 14:04:01
2023-10-25 14:04:01




2023-10-25 14:06:01
2023-10-25 14:06:01




2023-10-25 14:08:01
2023-10-25 14:08:01




2023-10-25 14:10:01
2023-10-25 14:10:01




2023-10-25 14:12:01

2023-10-25 14:12:01


2023-10-25 14:14:01


2023-10-25 14:14:01



2023-10-25 14:16:01
2023-10-25 14:16:01




2023-10-25 14:18:01
2023-10-25 14:18:01



2023-10-25 14:22:01


2023-10-25 14:24:01


2023-10-25 14:26:01


2023-10-25 14:28:01


2023-10-25 14:30:01


2023-10-25 14:32:01


2023-10-25 14:34:01


2023-10-25 14:36:01


2023-10-25 14:38:01


2023-10-25 14:40:01


2023-10-25 14:42:01


2023-10-25 14:44:01


2023-10-25 14:46:01


2023-10-25 14:48:02


2023-10-25 14:50:01


2023-10-25 14:52:01


2023-10-25 14:54:01


2023-10-25 14:56:01


2023-10-25 14:58:01


2023-10-25 15:00:01


2023-10-25 15:02:01


2023-10-25 15:04:01


2023-10-25 15:06:01


2023-10-25 15:08:01


2023-10-25 15:10:01


2023-10-25 15:12:01


2023-10-25 15:14:01


2023-10-25 15:16:01


2023-10-25 15:18:01


2023-10-25 15:20:01


2023-10-25 15:22:01


2023-10-25 15:24:01


2023-10-25 15:26:01


2023-10-25 15:28:01


2023-10-25 15:30:01


2023-10-25 15:32:01


2023-10-25 15:34:01


2023-10-25 15:36:01


2023-10-25 15:38:01


2023-10-25 15:40:01


2023-10-25 15:42:01


2023-10-25 15:44:01


2023-10-25 15:46:01


2023-10-25 15:48:01


2023-10-25 15:50:01


2023-10-25 15:52:01


2023-10-25 15:54:01


2023-10-25 15:56:01


2023-10-25 15:58:01


2023-10-25 16:00:01


2023-10-25 16:02:01


2023-10-25 16:04:01


2023-10-25 16:06:01


2023-10-25 16:08:01


2023-10-25 16:10:01


2023-10-25 16:12:01


2023-10-25 16:14:01


2023-10-25 16:16:01


2023-10-25 16:18:01


2023-10-25 16:20:05


2023-10-25 16:22:01


2023-10-25 16:24:01


2023-10-25 16:26:01


2023-10-25 16:28:01


2023-10-25 16:30:01


2023-10-25 16:32:01


2023-10-25 16:34:01


2023-10-25 18:20:01


2023-10-25 18:22:01


2023-10-25 18:24:01


2023-10-25 18:36:01


2023-10-25 18:38:01


2023-10-25 18:40:01


2023-10-25 18:42:01


2023-10-25 18:44:02


2023-10-25 18:46:01


2023-10-25 18:48:01


2023-10-25 18:50:01


2023-10-25 18:52:01

